version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./recordings:/workspaces/recordings
